### ISSUE TITLE
mruby_set_code with syntax error gives segmentation fault

### ISSUE THREAD

**Issue by yyamano** [matsumoto-r/ngx_mruby#185]
I get segmentation fault with the following configuration:

```
  location /foo {
    mruby_set_code $foo 'end';
  }
```

```
% ./build/nginx/sbin/nginx
INLINE CODE:1:3: syntax error, unexpected keyword_end
Segmentation fault
```

Here is a gdb backtrace. I have a patch to fix it and will send a pull request later.

```
% gdb ./build/nginx/sbin/nginx 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/vagrant/ngx_mruby/build/nginx/sbin/nginx...done.
(gdb) run
Starting program: /home/vagrant/ngx_mruby/./build/nginx/sbin/nginx 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
INLINE CODE:1:3: syntax error, unexpected keyword_end

Program received signal SIGSEGV, Segmentation fault.
mrb_irep_incref (mrb=mrb@entry=0xb33830, irep=irep@entry=0x0) at /home/vagrant/ngx_mruby/mruby/src/state.c:125
125		  irep->refcnt++;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.6.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 pcre-8.32-15.el7_2.1.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  mrb_irep_incref (mrb=mrb@entry=0xb33830, irep=irep@entry=0x0) at /home/vagrant/ngx_mruby/mruby/src/state.c:125
#1  0x0000000000505dd4 in mrb_proc_new (mrb=mrb@entry=0xb33830, irep=0x0) at /home/vagrant/ngx_mruby/mruby/src/proc.c:32
#2  0x0000000000518797 in mrb_generate_code (mrb=0xb33830, p=p@entry=0xbbc670)
    at /home/vagrant/ngx_mruby/mruby/mrbgems/mruby-compiler/core/codegen.c:2888
#3  0x00000000004ce927 in ngx_http_mruby_shared_state_compile (cf=cf@entry=0x7fffffffe020, state=0xb24628, code=0xbccb60)
    at /home/vagrant/ngx_mruby/src/http/ngx_http_mruby_module.c:923
#4  0x00000000004d0546 in ngx_http_mruby_set_inner (cf=0x7fffffffe020, cmd=<optimized out>, conf=<optimized out>, 
    type=type@entry=NGX_MRB_CODE_TYPE_STRING) at /home/vagrant/ngx_mruby/src/http/ngx_http_mruby_module.c:1688
#5  0x00000000004d0697 in ngx_http_mruby_set_inline (cf=<optimized out>, cmd=<optimized out>, conf=<optimized out>)
    at /home/vagrant/ngx_mruby/src/http/ngx_http_mruby_module.c:1719
#6  0x0000000000465b64 in ngx_conf_handler (last=0, cf=0x7fffffffe020) at src/core/ngx_conf_file.c:427
#7  ngx_conf_parse (cf=cf@entry=0x7fffffffe020, filename=filename@entry=0x0) at src/core/ngx_conf_file.c:283
#8  0x00000000004829af in ngx_http_core_location (cf=0x7fffffffe020, cmd=<optimized out>, dummy=<optimized out>)
    at src/http/ngx_http_core_module.c:3256
#9  0x0000000000465b64 in ngx_conf_handler (last=1, cf=0x7fffffffe020) at src/core/ngx_conf_file.c:427
#10 ngx_conf_parse (cf=cf@entry=0x7fffffffe020, filename=filename@entry=0x0) at src/core/ngx_conf_file.c:283
#11 0x0000000000482c1b in ngx_http_core_server (cf=0x7fffffffe020, cmd=<optimized out>, dummy=<optimized out>)
    at src/http/ngx_http_core_module.c:3028
#12 0x0000000000465b64 in ngx_conf_handler (last=1, cf=0x7fffffffe020) at src/core/ngx_conf_file.c:427
#13 ngx_conf_parse (cf=cf@entry=0x7fffffffe020, filename=filename@entry=0x0) at src/core/ngx_conf_file.c:283
#14 0x000000000047e2f9 in ngx_http_block (cf=0x7fffffffe020, cmd=<optimized out>, conf=<optimized out>)
    at src/http/ngx_http.c:237
#15 0x0000000000465b64 in ngx_conf_handler (last=1, cf=0x7fffffffe020) at src/core/ngx_conf_file.c:427
#16 ngx_conf_parse (cf=cf@entry=0x7fffffffe020, filename=filename@entry=0xb1b568) at src/core/ngx_conf_file.c:283
#17 0x00000000004635da in ngx_init_cycle (old_cycle=old_cycle@entry=0x7fffffffe0c0) at src/core/ngx_cycle.c:274
#18 0x0000000000455932 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:276
``

**Comment by matsumoto-r** [comment]
Thanks always!
