### ISSUE TITLE
[SEGV] ngx_mruby in OS X El Capitan often crashes

### ISSUE THREAD

**Issue by hfm** [matsumoto-r/ngx_mruby#213]
ngx_mruby in OS X El Capitan frequently causes SEGV. Especially, [`/inter_var_file` test](https://github.com/matsumoto-r/ngx_mruby/blob/v1.18.4/test/t/ngx_mruby.rb#L47-L50) tends to cause SEGV.

```console
$ sudo gdb build/nginx/sbin/nginx
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin15.5.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/nginx/sbin/nginx...done.
(gdb) r
Starting program: /Users/usr0600296/src/github.com/matsumoto-r/ngx_mruby/build/nginx/sbin/nginx
"[15697] init master process"
2016/09/20 14:55:08 [notice] 15697#0: using the "kqueue" event method
"ngx_mruby: STREAM: mruby_stream_init_code"
2016/09/20 14:55:08 [notice] 15697#0: nginx/1.11.4
2016/09/20 14:55:08 [notice] 15697#0: built by clang 8.0.0 (clang-800.0.38)
2016/09/20 14:55:08 [notice] 15697#0: OS: Darwin 15.6.0
2016/09/20 14:55:08 [notice] 15697#0: hw.ncpu: 4
2016/09/20 14:55:08 [notice] 15697#0: net.inet.tcp.sendspace: 131072
2016/09/20 14:55:08 [notice] 15697#0: kern.ipc.somaxconn: 128
2016/09/20 14:55:08 [notice] 15697#0: getrlimit(RLIMIT_NOFILE): 4864:9223372036854775807
2016/09/20 14:55:08 [info] 15697#0: ngx_mruby INFO ngx_mrb_run_cycle:726: mrb_run
"[15697] init worker process from inline code"
"ngx_mruby: STREAM: mruby_stream_init_worker_code"
```

Executing`curl -v 127.0.0.1:58080/inter_var_file`, ngx_mruby frequently causes SEGV like the following:

```
2016/09/20 14:55:21 [info] 15697#0: *2 ngx_mruby INFO ngx_mrb_run:827: mrb_run info: rputs_chain is null and return NGX_OK, client: 127.0.0.1, server: localhost, request: "GET /inter_var_file HTTP/1.1", host: "127.0.0.1:58080"
2016/09/20 14:55:21 [info] 15697#0: *2 ngx_mruby INFO ngx_mrb_run:807: mrb_run info: return value=(400), client: 127.0.0.1, server: localhost, request: "GET /inter_var_file HTTP/1.1", host: "127.0.0.1:58080"
2016/09/20 14:55:21 [info] 15697#0: *2 ngx_mruby INFO ngx_mrb_run:780: mrb_run info: ai=82, client: 127.0.0.1, server: localhost, request: "GET /inter_var_file HTTP/1.1", host: "127.0.0.1:58080"

Program received signal SIGSEGV, Segmentation fault.
0x0000000100095b08 in ngx_mrb_rputs (mrb=0x10061dca0, self=<error reading variable: access outside bounds of object referenced via synthetic pointer>)
    at /Users/usr0600296/src/github.com/matsumoto-r/ngx_mruby/src/http/ngx_http_mruby_core.c:144
144       (*chain->last)->buf = b;
```
</details>

backtrace

```
(gdb) bt
#0  0x0000000100095b08 in ngx_mrb_rputs (mrb=0x10061dca0, self=<error reading variable: access outside bounds of object referenced via synthetic pointer>)
    at /Users/usr0600296/src/github.com/matsumoto-r/ngx_mruby/src/http/ngx_http_mruby_core.c:144
#1  0x00000001000c8846 in mrb_vm_exec (mrb=<optimized out>, proc=0x1008a9c50, pc=<optimized out>)
    at /Users/usr0600296/src/github.com/matsumoto-r/ngx_mruby/mruby/src/vm.c:1150
#2  0x00000001000915cd in ngx_mrb_run (r=0x10083d7e0, state=0x1008aab50, code=<optimized out>, cached=<optimized out>, result=<optimized out>)
    at /Users/usr0600296/src/github.com/matsumoto-r/ngx_mruby/src/http/ngx_http_mruby_module.c:783
#3  0x000000010009126a in ngx_http_mruby_content_handler (r=0x1008aad18)
    at /Users/usr0600296/src/github.com/matsumoto-r/ngx_mruby/src/http/ngx_http_mruby_module.c:1975
#4  0x0000000100035255 in ngx_http_core_content_phase (r=0x1008aab50, ph=0x1008aad18) at src/http/ngx_http_core_module.c:1375
#5  0x0000000100033a55 in ngx_http_core_run_phases (r=0x10083d7e0) at src/http/ngx_http_core_module.c:845
#6  ngx_http_handler (r=<optimized out>) at src/http/ngx_http_core_module.c:828
#7  0x000000010003d969 in ngx_http_process_request (r=0x10061dca0) at src/http/ngx_http_request.c:1914
#8  0x000000010003ede3 in ngx_http_process_request_line (rev=<optimized out>) at src/http/ngx_http_request.c:1026
#9  0x000000010002984d in ngx_kqueue_process_events (cycle=<optimized out>, timer=<optimized out>, flags=0) at src/event/modules/ngx_kqueue_module.c:669
#10 0x0000000100020e73 in ngx_process_events_and_timers (cycle=0x10061dca0) at src/event/ngx_event.c:242
#11 0x00000001000282fb in ngx_single_process_cycle (cycle=<optimized out>) at src/os/unix/ngx_process_cycle.c:309
#12 0x0000000100001f4d in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:364
```

list

```
(gdb) l
139       }
140       b = ngx_calloc_buf(r->pool);
141       if (b == NULL) {
142         mrb_raise(mrb, E_RUNTIME_ERROR, "failed to allocate memory");
143       }
144       (*chain->last)->buf = b;
145       (*chain->last)->next = NULL;
146
147       str = ngx_pstrdup(r->pool, &ns);
148       if (str == NULL) {
```

**Comment by matsumoto-r** [comment]
Thank you for your report. I fixed by #215 .
